name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6"
    
    - name: Print environment
      run: |
        printf "Swift: %s\n" "$(swift --version | head -n1)"
        printf "macOS: %s\n" "$(sw_vers -productVersion)"
        
    - name: Build
      run: swift build -c release
      
    - name: Test
      run: swift test